spring.application.name=OnlineShop

spring.datasource.url=jdbc:postgresql://localhost:5432/shopping_app
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Aditi321}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT secret (add karna hoga JWT filter ke liye)
jwt.secret=${JWT_SECRET:your-256-bit-secret-change-this-in-production}
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

superadmin.email=${SUPERADMIN_EMAIL:superadmin@onlineshop.com}
superadmin.password=${SUPERADMIN_PASSWORD:ChangeMe@123}